{% set name = "stochastic" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c166b5f7707d0857597125dbffa03f59cb1ffb668cb027396d4cca69b3df1b7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6,<4
  run:
    - numpy >=1.17,<2.0
    - python >=3.6,<4
    - scipy >=1.3,<2.0

test:
  imports:
    - stochastic
    - stochastic.processes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crflynn/stochastic
  summary: Generate realizations of stochastic processes in python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://stochastic.readthedocs.io/en/latest/
  dev_url: https://github.com/crflynn/stochastic

extra:
  recipe-maintainers:
    - BastianZim
